/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/about` | `/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/read` | `/read`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tabLayout` | `/tabLayout`; params?: Router.UnknownInputParams; } | { pathname: `/components`; params?: Router.UnknownInputParams; } | { pathname: `/components/read/pageDisplay`; params?: Router.UnknownInputParams; } | { pathname: `/components/read/wordDisplay`; params?: Router.UnknownInputParams; } | { pathname: `/components/read/read-styles/styles`; params?: Router.UnknownInputParams; } | { pathname: `/components/search/LineSearch`; params?: Router.UnknownInputParams; } | { pathname: `/components/search/WordSearch`; params?: Router.UnknownInputParams; } | { pathname: `/line-details/[start]/[end]`, params: Router.UnknownInputParams & { start: string | number;end: string | number; } } | { pathname: `/word-details/[word]`, params: Router.UnknownInputParams & { word: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/about` | `/about`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/read` | `/read`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tabLayout` | `/tabLayout`; params?: Router.UnknownOutputParams; } | { pathname: `/components`; params?: Router.UnknownOutputParams; } | { pathname: `/components/read/pageDisplay`; params?: Router.UnknownOutputParams; } | { pathname: `/components/read/wordDisplay`; params?: Router.UnknownOutputParams; } | { pathname: `/components/read/read-styles/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/components/search/LineSearch`; params?: Router.UnknownOutputParams; } | { pathname: `/components/search/WordSearch`; params?: Router.UnknownOutputParams; } | { pathname: `/line-details/[start]/[end]`, params: Router.UnknownOutputParams & { start: string;end: string; } } | { pathname: `/word-details/[word]`, params: Router.UnknownOutputParams & { word: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/about${`?${string}` | `#${string}` | ''}` | `/about${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/read${`?${string}` | `#${string}` | ''}` | `/read${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/search${`?${string}` | `#${string}` | ''}` | `/search${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tabLayout${`?${string}` | `#${string}` | ''}` | `/tabLayout${`?${string}` | `#${string}` | ''}` | `/components${`?${string}` | `#${string}` | ''}` | `/components/read/pageDisplay${`?${string}` | `#${string}` | ''}` | `/components/read/wordDisplay${`?${string}` | `#${string}` | ''}` | `/components/read/read-styles/styles${`?${string}` | `#${string}` | ''}` | `/components/search/LineSearch${`?${string}` | `#${string}` | ''}` | `/components/search/WordSearch${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/about` | `/about`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/read` | `/read`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/search` | `/search`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tabLayout` | `/tabLayout`; params?: Router.UnknownInputParams; } | { pathname: `/components`; params?: Router.UnknownInputParams; } | { pathname: `/components/read/pageDisplay`; params?: Router.UnknownInputParams; } | { pathname: `/components/read/wordDisplay`; params?: Router.UnknownInputParams; } | { pathname: `/components/read/read-styles/styles`; params?: Router.UnknownInputParams; } | { pathname: `/components/search/LineSearch`; params?: Router.UnknownInputParams; } | { pathname: `/components/search/WordSearch`; params?: Router.UnknownInputParams; } | `/line-details/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}` | `/word-details/${Router.SingleRoutePart<T>}` | { pathname: `/line-details/[start]/[end]`, params: Router.UnknownInputParams & { start: string | number;end: string | number; } } | { pathname: `/word-details/[word]`, params: Router.UnknownInputParams & { word: string | number; } };
    }
  }
}
